version: "2.2"

services:
  api:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: "/static/"
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    depends_on:
      - db
      - redis
      - dd-agent
    volumes:
      # - ./tenants/:/app/tenants:Z
      - /app/saleor/static/assets
      - /app/templates/templated_email/compiled
      - saleor-media:/app/media
      - sockets:/var/run/datadog
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ./common.env

  db:
    image: library/postgres:11-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: library/redis:5.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: "/static/"
    command: celery --app saleor.celeryconf:app worker --loglevel=INFO -E
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file: ./common.env
    depends_on:
      - redis
    volumes:
      # - ./tenants/:/app/tenants:Z
      - /app/templates/templated_email/compiled
      - saleor-media:/app/media

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
    networks:
      - saleor-backend-tier

  # Versions:
  # docker run --rm quay.io/skopeo/stable list-tags docker://gcr.io/datadoghq/agent
  #
  # DANGER: do not set the API key unless you absolutely need to see and analyze the traces.
  #         If you need to check traces are being sent, set DD_LOGGING_LEVEL=DEBUG to Saleor
  #         and then watch logs of the agent and of Saleor as it provides enough information
  #         and will not crash when an invalid API key is passed.
  dd-agent:
    image: gcr.io/datadoghq/agent:7
    ports:
      - "8126:8126/tcp"
    volumes:
      - sockets:/var/run/datadog
    environment:
      DD_APM_ENABLED: "true"
      DD_BIND_HOST: "0.0.0.0"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "false"
      DD_DOGSTATSD_SOCKET: /var/run/datadog/dsd.socket
      # Do not edit the compose-file directly: refer to `.env`
      DD_API_KEY: ${DD_API_KEY}

  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:
  sockets:
    driver: local

networks:
  saleor-backend-tier:
    driver: bridge
