name: "Linters: DogStatsD"

on:
  push:
    paths:
      - dogstatsd-metric-exporter/**.py
      - .github/workflows/linters-dogstatsd-metric-exporter.yaml

defaults:
  run:
    shell: bash
    working-directory: dogstatsd-metric-exporter/

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Development
        run: python -m pip install -e .'[linters]'

      - name: Run Linters
        run: make clean

      - name: Check Differences
        run: |
          git status --porcelain=v1 -uno > /tmp/git-diffs
          awk 'END { exit NR > 0; }' < /tmp/git-diffs || {
            echo 'Found differences:' 1>&2
            cat /tmp/git-diffs 1>&2
            exit 1
          }
