name: "Tests: sbom-generator"
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - .github/workflows/test-sbom-generator.yaml
      - ./sbom-generator/**
  push:
    branches: [main]
    paths:
      - .github/workflows/test-sbom-generator.yaml
      - ./sbom-generator/**

permissions: {}

jobs:
  main:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: ./sbom-generator

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: ./sbom-generator

      - name: Run Tests
        run: scripts/test-cdxgen-support.sh --cdxgen-version 11.6.0
